modify Dockerfile to fix go build issue
weihesdlegend/Vacation-Planner pull request #158
Opened 2020-11-09 15:43 UTC by sananand007

## Description
We do not need to do a `cd main` any more as the main.go is in the working directory

## Root Cause
There was no `main` directory which was causing the `go build` step to fail in the Docker build step

## Solution
Changed the `Dockerfil` to take out the `cd main` 

## Testing
NR

## Final Checks
- [X] Have you removed commented code ?
- [ ] Have you used gofmt to format your code ?
- [ ] You have added unit tests

2020-11-09 18:53 UTC, weihesdlegend requested changes

2020-11-09 18:53 UTC, weihesdlegend commented on Dockerfile
>  RUN ls -al
Is this needed?

2020-11-09 18:53 UTC, weihesdlegend commented on Dockerfile
> +RUN ls -altr &&  go build -v .
Go build -v . Should be sufficient

2020-11-16 21:56 UTC, sananand007 commented
@weihesdlegend Are all changes in ? Could we approve

2020-11-16 22:47 UTC, weihesdlegend commented
> @weihesdlegend Are all changes in ? Could we approve

No, where is go test? Do we want to have run server part also?

2020-11-17 03:00 UTC, sananand007 commented
Go test is a separate test, look at the build logs. Do we need to have the test run the docker image? Any reasons for that

2020-11-17 03:25 UTC, weihesdlegend commented
> Go test is a separate test, look at the build logs. Do we need to have the tests run within the docker image? Any reasons for that
> 
> ```
> function run_docker() {
> 	docker run --rm unwindtest:$BUILD_NUMBER /bin/sh -c "echo $PWD && \
> 		go test -v ./..."
> }
> ```

That's fair, but can you try to make it run under some port with `CMD`?

2020-12-07 05:23 UTC, weihesdlegend commented on .gitignore
> +planner-app/
remove this line since it does not exist on master

2020-12-07 16:46 UTC, weihesdlegend approved these changes
LGTM

2020-12-07 16:47 UTC, merged